"""
html_export.py — Convert LLM Markdown output to styled HTML documents
"""
import re
from datetime import datetime


def markdown_to_html(markdown_text, title="Document", project_name="", doc_type="SRS"):
    body_html = _convert_markdown(markdown_text)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'Segoe UI',Arial,sans-serif; font-size:14px; line-height:1.7; color:#1a202c; background:#fff; max-width:900px; margin:0 auto; padding:40px 50px; }}
  .doc-header {{ background:#1a365d; color:#fff; padding:35px 40px; margin:-40px -50px 36px -50px; border-bottom:4px solid #2b6cb0; }}
  .doc-header h1 {{ font-size:26px; font-weight:700; margin-bottom:6px; }}
  .doc-header .sub {{ font-size:15px; opacity:.85; margin-bottom:14px; }}
  .doc-header .meta {{ font-size:11px; opacity:.6; display:flex; gap:20px; }}
  h1 {{ font-size:22px; font-weight:700; color:#1a365d; margin:32px 0 14px; padding-bottom:7px; border-bottom:2px solid #bee3f8; }}
  h2 {{ font-size:18px; font-weight:600; color:#2a4a7f; margin:26px 0 10px; padding-bottom:5px; border-bottom:1px solid #e2e8f0; }}
  h3 {{ font-size:15px; font-weight:600; color:#1a202c; margin:20px 0 8px; }}
  h4 {{ font-size:13px; font-weight:600; color:#4a5568; margin:16px 0 6px; }}
  p {{ margin:8px 0; }}
  ul,ol {{ margin:8px 0 8px 22px; }}
  li {{ margin:3px 0; }}
  li::marker {{ color:#2b6cb0; }}
  table {{ width:100%; border-collapse:collapse; margin:14px 0; font-size:13px; }}
  thead th {{ background:#1a365d; color:#fff; padding:9px 12px; text-align:left; font-size:11px; text-transform:uppercase; letter-spacing:.4px; }}
  tbody td {{ padding:8px 12px; border-bottom:1px solid #e2e8f0; vertical-align:top; }}
  tbody tr:nth-child(even) {{ background:#f7fafc; }}
  tbody tr:hover {{ background:#bee3f8; }}
  code {{ font-family:'Consolas',monospace; background:#f7fafc; padding:1px 5px; border-radius:3px; font-size:12px; border:1px solid #e2e8f0; }}
  pre {{ background:#1a202c; color:#e2e8f0; padding:14px 18px; border-radius:6px; overflow-x:auto; margin:12px 0; font-size:12px; line-height:1.5; }}
  pre code {{ background:none; border:none; padding:0; color:inherit; }}
  blockquote {{ border-left:4px solid #2b6cb0; background:#f7fafc; padding:10px 14px; margin:12px 0; color:#4a5568; }}
  strong {{ font-weight:600; }}
  hr {{ border:none; border-top:1px solid #e2e8f0; margin:24px 0; }}
  .req-id {{ display:inline-block; background:#bee3f8; color:#2b6cb0; padding:1px 7px; border-radius:3px; font-family:'Consolas',monospace; font-size:11px; font-weight:500; }}
  .doc-footer {{ margin-top:36px; padding-top:14px; border-top:1px solid #e2e8f0; font-size:11px; color:#718096; display:flex; justify-content:space-between; }}
  @media print {{ body {{ padding:20px; max-width:100%; }} .doc-header {{ margin:-20px -20px 20px; }} table {{ page-break-inside:avoid; }} }}
</style>
</head>
<body>
<div class="doc-header">
  <h1>{title}</h1>
  <div class="sub">{project_name}</div>
  <div class="meta">
    <span>Type: {doc_type}</span>
    <span>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</span>
    <span>Status: DRAFT</span>
  </div>
</div>
{body_html}
<div class="doc-footer">
  <span>Generated by SRS/SDD RAG Pipeline</span>
  <span>{datetime.now().strftime('%Y-%m-%d')}</span>
</div>
</body>
</html>"""
    return html


def _convert_markdown(text):
    lines = text.split("\n")
    parts = []
    in_table = False
    table_rows = []
    in_code = False
    code_lines = []
    in_list = False
    list_tag = None

    for line in lines:
        s = line.strip()

        if s.startswith("```"):
            if in_code:
                parts.append(f'<pre><code>{chr(10).join(code_lines)}</code></pre>')
                code_lines = []
                in_code = False
            else:
                _close_list(parts, in_list, list_tag); in_list = False
                in_code = True
            continue
        if in_code:
            code_lines.append(_esc(s))
            continue

        if not s:
            if in_table and table_rows:
                parts.append(_mk_table(table_rows)); table_rows = []; in_table = False
            _close_list(parts, in_list, list_tag); in_list = False
            continue

        if s.startswith("|") and s.endswith("|"):
            if all(c in "-| :" for c in s): continue
            table_rows.append([c.strip() for c in s.split("|")[1:-1]])
            in_table = True
            continue
        if in_table and table_rows:
            parts.append(_mk_table(table_rows)); table_rows = []; in_table = False

        if s.startswith("#### "):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<h4>{_fmt(s[5:])}</h4>')
        elif s.startswith("### "):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<h3>{_fmt(s[4:])}</h3>')
        elif s.startswith("## "):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<h2>{_fmt(s[3:])}</h2>')
        elif s.startswith("# "):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<h1>{_fmt(s[2:])}</h1>')
        elif s.startswith("> "):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<blockquote>{_fmt(s[2:])}</blockquote>')
        elif s in ("---", "***", "___"):
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append('<hr>')
        elif s.startswith("- ") or s.startswith("* "):
            if not in_list or list_tag != "ul":
                _close_list(parts, in_list, list_tag); in_list = True; list_tag = "ul"; parts.append("<ul>")
            parts.append(f'<li>{_fmt(s[2:])}</li>')
        elif re.match(r"^\d+\.\s", s):
            if not in_list or list_tag != "ol":
                _close_list(parts, in_list, list_tag); in_list = True; list_tag = "ol"; parts.append("<ol>")
            parts.append(f'<li>{_fmt(re.sub(r"^d+.s", "", s))}</li>')
        else:
            _close_list(parts, in_list, list_tag); in_list = False
            parts.append(f'<p>{_fmt(s)}</p>')

    if in_table and table_rows: parts.append(_mk_table(table_rows))
    _close_list(parts, in_list, list_tag)
    return "\n".join(parts)


def _close_list(parts, in_list, tag):
    if in_list and tag: parts.append(f'</{tag}>')

def _esc(t):
    return t.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")

def _fmt(t):
    t = _esc(t)
    t = re.sub(r'`([^`]+)`', r'<code>\1</code>', t)
    t = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', t)
    t = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', t)
    t = re.sub(r'\*(.+?)\*', r'<em>\1</em>', t)
    t = re.sub(r'\b((?:SRS|HRS|SDD|SYRS|REQ|FR|NFR|SAF|PERF|IF|CON|EXT)[-_](?:FUNC|PERF|IF|SAF|CON|REG|NFR)?[-_]?\d{1,5})\b', r'<span class="req-id">\1</span>', t)
    return t

def _mk_table(rows):
    if not rows: return ""
    h = '<table><thead><tr>' + ''.join(f'<th>{_fmt(c)}</th>' for c in rows[0]) + '</tr></thead><tbody>'
    for r in rows[1:]:
        h += '<tr>' + ''.join(f'<td>{_fmt(c)}</td>' for c in r) + '</tr>'
    return h + '</tbody></table>'
